name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.EC2_HOST}}
        username: ubuntu
        key: ${{secrets.EC2_SSH_KEY}} 
        script: |
          cd /var/www/your-app
          git pull origin main
          npm install
          pm2 restart all
