name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Server
        run: |
          ssh ubuntu@18.206.118.136 << 'EOF'
            cd /var/www/your-app
            git pull origin main
            npm install
            tsc
            pm2 restart your-app-name
            pm2 save
          EOF
